class Va(Exception):
    pass

    def add():
        try:
            a = int(input("Enter first Number : "))
            b = int(input("Enter Second Number : "))
            add = a+b
            print(add)
        except Exception as e:
            print("Enter integer.")



# def add():
#     try:
#         a = int(input("Enter first Number : "))
#         b = int(input("Enter Second Number : "))
#         add = a+b
#         print(add)
#     except Exception as e:
#         print("Enter integer.")

# add()