class RecognizeError(Exception):
#     pass

# def add():
#     try:
#         a = int(input("Enter first Number : "))
#         b = int(input("Enter Second Number : "))
#         add = a+b
#         print(add)
#     except RecognizeError as e:
#         print("Enter integer.",e)

# add()
